export const cardData = [
  {
    id: 0,
    Name: "Bajra",
    Date: "24-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/JBF5dzB2cpnmr2Fx6",
  },
  {
    id: 1,
    Name: "Circulatory System",
    Date: "24-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/LKfnfFsyrxxoRsFA9",
  },
  {
    id: 2,
    Name: "W.T.O",
    Date: "25-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/2jsKW1mkWDex2YPx5",
  },
  {
    id: 3,
    Name: "Conduction of impulse",
    Date: "25-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/XXv3WZ6VudTbpX439",
  },
  {
    id: 4,
    Name: "ICAR",
    Date: "25-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/JkB8c17ADdBy6TPz8",
  },
  {
    id: 5,
    Name: "EIC & CSW",
    Date: "27-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/kGWmfAqpKtC65zer8",
  },
  {
    id: 6,
    Name: "Pulses",
    Date: "27-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/wG4NRHxspnCSQnxD9",
  },
  {
    id: 7,
    Name: "Onion",
    Date: "28-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/pzb5KF4Zcpvm53uc9",
  },
  {
    id: 8,
    Name: "ICMR& Overview of FSSAI",
    Date: "28-Feb",
    Month: "Feb",
    courseLink: "https://forms.gle/VmzeQYMNK1JJvEB96",
  },
  {
    id: 31,
    Name: "Mango & Ber",
    Date: "02-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/RYC18ymTs2iEoeH4A",
  },
  {
    id: 9,
    Name: "Bacteria (1)",
    Date: "02-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/mk5at26NXJoHnP8F9",
  },
  {
    id: 10,
    Name: "Citrus & Guava",
    Date: "03-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/vhtiYrYbrpAN9Qnb7",
  },
  {
    id: 11,
    Name: "Bacteria (2)",
    Date: "03-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/VWfcYyPUHMQtaeSm9",
  },
  {
    id: 12,
    Name: "Rose & Chilli",
    Date: "04-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/DAeeeHjB4x2Anaoa8",
  },
  {
    id: 13,
    Name: "Bacteria (3)",
    Date: "04-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/5UvFbAmfpDnGmAd46",
  },
  {
    id: 14,
    Name: "ISABGOL AND ALOVERA",
    Date: "08-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/bPJGApA5GN9LCa4j6",
  },
  {
    id: 15,
    Name: "Mold (1)",
    Date: "08-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/Z9qWxHtV1bSAVkKt5",
  },
  {
    id: 16,
    Name: "Agmark",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/oe7Aev7ekJbESS2c6",
  },
  {
    id: 17,
    Name: "Mustard",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/UwrtK8nfvVqwE1Eq7",
  },
  {
    id: 18,
    Name: "WHO",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/VEQGqsqz91jwWsDE7",
  },
  {
    id: 19,
    Name: "Ground nut",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/1Gf2BuoyU3mPDFpV6",
  },
  {
    id: 32,
    Name: "Test link is live",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/HkimYjRgcTCnW4xs9",
  },
  {
    id: 20,
    Name: "CUMIN AND FENUGREEK",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/HkimYjRgcTCnW4xs9",
  },
  {
    id: 21,
    Name: "Mold (2)",
    Date: "09-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/ShcQHtrxi3WcSWhK8",
  },
  {
    id: 22,
    Name: "CORIANDER AND FENNEL",
    Date: "10-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/ZciUFn2uivEkhBfD9",
  },
  {
    id: 23,
    Name: "Yeast (1)",
    Date: "10-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/dZGTwLJH1vSKXfjA7",
  },
  {
    id: 24,
    Name: "CROP PHYSIOLOGY",
    Date: "11-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/34GGVRLz9haeGqFDA",
  },
  {
    id: 25,
    Name: "Yeast (2)",
    Date: "11-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/RkAu7HYEdt2S2WC67",
  },
  {
    id: 26,
    Name: "Seed Science",
    Date: "13-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/7qv3dQVUQ6xCFhPV6",
  },
  {
    id: 27,
    Name: "Factor affecting the growth of microorganisms",
    Date: "13-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/nzFMwK6rrdtSB28h6",
  },
  {
    id: 28,
    Name: "Soil fertility and management of problematic",
    Date: "14-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/pAesKbMkJUw6YMCH7",
  },
  {
    id: 29,
    Name: "factors affecting the growth of microorganisms(2)",
    Date: "14-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/UZ7G3eG6ZBmaBRU46",
  },
  {
    id: 30,
    Name: "Some important food spoilage microorganisms-cereals and honey",
    Date: "15-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/6yWVHGSse4q4",
  },
  {
    id: 33,
    Name: "Introduction to Dry Land Farming and Agroforestry",
    Date: "15-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/mWakbag2JtetDNfL7",
  },
  {
    id: 34,
    Name: "Some Important Food Spoilage Microorganisms - Fruits and Vegetables",
    Date: "16-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/9HG9Nq9LC8VSBNb88",
  },
  {
    id: 35,
    Name: "Salient Feature of Agriculture with Special Reference to Rajasthan",
    Date: "16-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/H3Mi3jALmVbbxkNc9",
  },
  {
    id: 36,
    Name: "Some Important Food Spoilage Microorganisms - Eggs and Poultry",
    Date: "17-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/8zGnMAP5fxgQhnhT9",
  },
  {
    id: 37,
    Name: "Important Diseases and Pests of Major Crops and Management",
    Date: "17-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/dtAAeDg4Q2ensDXb8",
  },
  {
    id: 38,
    Name: "Some Important Food Spoilage Microorganisms - Canned Foods",
    Date: "18-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/599AwrURRYs9Z2ft8",
  },
  {
    id: 39,
    Name: "Importance of Livestock in Economy of Rajasthan",
    Date: "18-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/SWYxFoeJdE4r1pmt6",
  },
  {
    id: 40,
    Name: "ISO",
    Date: "19-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/xbLRGBmfTPgi7XHv7",
  },
  {
    id: 41,
    Name: "Some Important Food Spoilage Microorganisms - Fish and Other Seafood Products",
    Date: "20-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/Rn4KapDNvbdr9JJZ6",
  },
  {
    id: 42,
    Name: "Fundamentals of Livestock Production",
    Date: "20-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/5Rir3GuxuWUU62E37",
  },
  {
    id: 43,
    Name: "Onion",
    Date: "21-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/pekF8rLTFYqzBfU48",
  },
  {
    id: 44,
    Name: "fermentations -definition and types, sources of microorganisms",
    Date: "21-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/2jp2yWgrN5FqVMVR7",
  },
  {
    id: 45,
    Name: "FUNDAMENTALS OF POULTARY PRODUCTION",
    Date: "21-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/gYWfg8b3mH49TAxX6",
  },
  {
    id: 46,
    Name: "ARTIFICIAL INSEMINATION AND PREGNANT ANIMAL MANAGEMENT",
    Date: "23-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/5w5bQbTbu6w9GfEB8",
  },
  {
    id: 47,
    Name: "MICROORAGNISMS USED IN FOOD FERMNATION(1)",
    Date: "23-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/G7QBYPn9Zuhod4PWA",
  },
  {
    id: 48,
    Name: "Microorganisms used in food fermentation (2)",
    Date: "24-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/LEGbumiqF91fnxFG7",
  },
  {
    id: 49,
    Name: "IMPORTANT DISESES OF LIVESTOCK AND MANAGEMENT",
    Date: "25-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/8zCRnnXDBRz8ZvKv6",
  },
  {
    id: 50,
    Name: "Present status of milk and milk product",
    Date: "25-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/v9SpENiLdZJnE5nGA",
  },
  {
    id: 51,
    Name: "Fermented food types",
    Date: "27-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/68wmKkLkm2fVBgdq6",
  },
  {
    id: 52,
    Name: "methods of manufacture of vinegar, saurkraut ,soya suace",
    Date: "28-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/4B9Ehy7KtAaRRCzM9",
  },
  {
    id: 53,
    Name: "Milk production and quality of milk",
    Date: "28-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/yqpTRazk",
  },
  {
    id: 54,
    Name: "Milk processing",
    Date: "29-Mar",
    Month: "Mar",
    courseLink: "https://forms.gle/T6jix6JttrVcBBhB7",
  },
];
